{
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {},
    "cells": [
        {
            "cell_type": "code",
            "source": [
                "# prompt: from universal_ai import UniversalAISystem\n",
                "# # \ud83d\udd25 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0646\u0638\u0627\u0645\n",
                "# ai_system = UniversalAISystem()\n",
                "# print(\"\ud83d\ude80 \u062a\u0645 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0646\u0638\u0627\u0645 \u0628\u0646\u062c\u0627\u062d!\")\n",
                "# # \ud83d\ude80 \u0636\u0628\u0637 \u0627\u0644\u062a\u0637\u0628\u064a\u0642 \u0625\u0644\u0649 \u0627\u0644\u062a\u062f\u0627\u0648\u0644 \u0623\u0648 \u0623\u064a \u062a\u0637\u0628\u064a\u0642 \u0622\u062e\u0631\n",
                "# print(ai_system.set_application_mode(\"trading\"))\n",
                "\n",
                "# Install necessary libraries (if not already installed)\n",
                "!pip install universal-ai  # Replace 'universal-ai' with the actual package name if different\n",
                "\n",
                "from universal_ai import UniversalAISystem\n",
                "\n",
                "# \ud83d\udd25 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0646\u0638\u0627\u0645\n",
                "ai_system = UniversalAISystem()\n",
                "print(\"\ud83d\ude80 \u062a\u0645 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0646\u0638\u0627\u0645 \u0628\u0646\u062c\u0627\u062d!\")\n",
                "\n",
                "# \ud83d\ude80 \u0636\u0628\u0637 \u0627\u0644\u062a\u0637\u0628\u064a\u0642 \u0625\u0644\u0649 \u0627\u0644\u062a\u062f\u0627\u0648\u0644 \u0623\u0648 \u0623\u064a \u062a\u0637\u0628\u064a\u0642 \u0622\u062e\u0631\n",
                "try:\n",
                "    print(ai_system.set_application_mode(\"trading\"))\n",
                "except Exception as e:\n",
                "    print(f\"An error occurred: {e}\")\n"
            ],
            "metadata": {
                "colab": {
                    "base_uri": "https://localhost:8080/",
                    "height": 777
                },
                "id": "473aUgnO8Oyp",
                "executionInfo": {
                    "status": "error",
                    "timestamp": 1747312513941,
                    "user_tz": -180,
                    "elapsed": 3144,
                    "user": {
                        "displayName": "\u0643\u0644 \u0634\u064a\u0626",
                        "userId": "12897848663942064459"
                    }
                },
                "outputId": "90988bf7-0883-4b69-b802-6a74ff3a4694"
            },
            "execution_count": 4,
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stdout",
                    "text": [
                        "Collecting universal-ai\n",
                        "  Downloading universal_ai-0.1.0-py3-none-any.whl.metadata (347 bytes)\n",
                        "Downloading universal_ai-0.1.0-py3-none-any.whl (1.1 kB)\n",
                        "Installing collected packages: universal-ai\n",
                        "Successfully installed universal-ai-0.1.0\n"
                    ]
                },
                {
                    "output_type": "error",
                    "ename": "ImportError",
                    "evalue": "cannot import name 'UniversalAISystem' from 'universal_ai' (/usr/local/lib/python3.11/dist-packages/universal_ai/__init__.py)",
                    "traceback": [
                        "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
                        "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
                        "\u001b[0;32m<ipython-input-4-18836216635e>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"pip install universal-ai  # Replace 'universal-ai' with the actual package name if different\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     10\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 11\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0muniversal_ai\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mUniversalAISystem\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     12\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0;31m# \ud83d\udd25 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0646\u0638\u0627\u0645\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
                        "\u001b[0;31mImportError\u001b[0m: cannot import name 'UniversalAISystem' from 'universal_ai' (/usr/local/lib/python3.11/dist-packages/universal_ai/__init__.py)",
                        "",
                        "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
                    ],
                    "errorDetails": {
                        "actions": [
                            {
                                "action": "open_url",
                                "actionText": "Open Examples",
                                "url": "/notebooks/snippets/importing_libraries.ipynb"
                            }
                        ]
                    }
                }
            ]
        },
        {
            "cell_type": "code",
            "execution_count": null,
            "metadata": {
                "id": "KbT3WqSUJGEK"
            },
            "outputs": [],
            "source": [
                "# prompt: ---------------------------------------------------------------------------\n",
                "# FileNotFoundError                         Traceback (most recent call last)\n",
                "# <ipython-input-4-573eba60acfc> in <cell line: 0>()\n",
                "#       3 import os\n",
                "#       4\n",
                "# ----> 5 print(os.listdir(\"/content/ipynb\"))\n",
                "# FileNotFoundError: [Errno 2] No such file or directory: '/content/ipynb'\n",
                "\n",
                "import os\n",
                "\n",
                "print(os.listdir(\"/content\"))\n"
            ]
        }
    ]
}